dataset_path: /bigdata/RadImageNet/rin2d/radiology_ai/MR/brain/normal
experiment_name: radimagenet_pretrain_mript-level
device: "cuda:1"
input_height: 128
input_width: 128
val_split: 0.1
batch_size: 6
num_epochs: 5
learning_rate: 1e-5
loss: mixed_l1_grad
num_workers: 4
prefetch_factor: 2
persistent_workers: true
use_precomputed_mask: false
seed: none
mode: level
path_model: ./saved_models/
resume_from: none